DROP TABLE barcode; 
DROP TABLE orderline; 
DROP TABLE stock; 
DROP TABLE orderinfo; 
DROP TABLE item; 
DROP TABLE customer; 
DROP SEQUENCE customer_customer_id_seq; 
DROP SEQUENCE item_item_id_seq; 
DROP SEQUENCE orderinfo_orderinfo_id_seq;